### ISSUE TITLE
Spacing calculation script - error 

### ISSUE THREAD

**Issue by stefano-casiraghi** [gbene/FracAbility#14] opened 2024-10-03 15:28 UTC
### Describe the bug, what's wrong, and what you expected.

When calculating the spacing for set_1, set_2 and set_3 joints the script gives an error like this one:  "ValueError: data length of (424) != required length (422)". 

### Steps to reproduce the bug.

```python
Insert code here
```

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Thu Oct 03 16:33:47 2024 W. Europe Daylight Time

                OS : Windows (10 10.0.22631 SP0 Multiprocessor Free)
            CPU(s) : 32
           Machine : AMD64
      Architecture : 64bit
               RAM : 127.7 GiB
       Environment : Python

  Python 3.10.14 | packaged by Anaconda, Inc. | (main, May  6 2024, 19:44:50)
  [MSC v.1916 64 bit (AMD64)]

       fracability : 1.5.2
           pyvista : 0.44.1
               vtk : 9.3.1
             numpy : 2.0.1
         geopandas : 1.0.1
           shapely : 2.0.5
             scipy : 1.14.0
           IPython : 8.26.0
        matplotlib : 3.9.1
            scooby : 0.10.0
--------------------------------------------------------------------------------
```

### Datasets

[Data.zip](https://github.com/user-attachments/files/17246473/Data.zip)

**Comment by gbene** [comment] 2024-10-23 20:08
This is probably related to precision and tolerance differences between vtk and shapely. 
I encountered this only with the spacing topology example because many "fractures" (scan line bits) inside the boundary have coinciding ends caused by the precise cut between the scan lines and fracture segments of the network. 
The problem is sort of resolved by a workaround that I have introduced. When calculating the topology for spacing you should add:

`frac_net.calculate_topology(only_boundary=True)`

This tells the backend to compute nodes of fractures concerning only the boundary. By the way this option can also be used in normal fracture networks when you are interested only in the statistical stuff. Using this option the number of nodes and intersections to check are much lower and thus the topological analysis is quicker!

**Closed as completed** 2024-10-23 20:09 UTC
Labels: bug
